name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v3

    - name: install deps
    - run:  yum install make -y
    - name: make
      run:  make
    - name: make check
      run:  make check
